import json

# Pipeline projects from seed
pipeline_projects = [
    {"id": "PRJ-101", "project_name": "Taj Coastal Resort Decking", "client_name": "Taj Hospitality", "location": "Candolim Beach", "city": "Goa", "state": "Goa", "country": "India", "financial_year": "FY 25-26", "month": 4, "day_bracket": "1-5", "category": "UltraShield Decking", "total_value": 4500000.0, "sq_ft": 10700.0, "discount_pct": 8.5, "days_pipeline_to_win": 42, "stage": "Win", "feedback_pending": 0, "feedback_notes": "Approved", "owner_name": "Rohan Verma"},
    {"id": "PRJ-102", "project_name": "DLF Luxury Penthouse Terrace", "client_name": "DLF Urban", "location": "Golf Course Ext", "city": "Gurugram", "state": "Haryana", "country": "India", "financial_year": "FY 25-26", "month": 4, "day_bracket": "6-10", "category": "Pergola & Cladding", "total_value": 2800000.0, "sq_ft": 5200.0, "discount_pct": 12.0, "days_pipeline_to_win": 0, "stage": "Pipeline", "feedback_pending": 1, "feedback_notes": "Architect sample requested", "owner_name": "Rohan Verma"},
    {"id": "PRJ-103", "project_name": "Prestige Golfshire Villa", "client_name": "Prestige Group", "location": "Nandi Hills", "city": "Bengaluru", "state": "Karnataka", "country": "India", "financial_year": "FY 25-26", "month": 5, "day_bracket": "11-15", "category": "UltraShield Decking", "total_value": 6200000.0, "sq_ft": 14500.0, "discount_pct": 7.0, "days_pipeline_to_win": 38, "stage": "Win", "feedback_pending": 0, "feedback_notes": "Commercial invoice released", "owner_name": "Super Administrator"},
    {"id": "PRJ-104", "project_name": "Oberoi Sky City Promenade", "client_name": "Oberoi Realty", "location": "Borivali East", "city": "Mumbai", "state": "Maharashtra", "country": "India", "financial_year": "FY 25-26", "month": 5, "day_bracket": "16-20", "category": "Exterior Cladding", "total_value": 3900000.0, "sq_ft": 8900.0, "discount_pct": 10.0, "days_pipeline_to_win": 0, "stage": "Pipeline", "feedback_pending": 1, "feedback_notes": "Color finish approval awaited", "owner_name": "Rohan Verma"},
    {"id": "PRJ-105", "project_name": "Amanora Park Town Boulevard", "client_name": "Amanora Group", "location": "Hadapsar", "city": "Pune", "state": "Maharashtra", "country": "India", "financial_year": "FY 25-26", "month": 6, "day_bracket": "21-25", "category": "Composite Deck Tiles", "total_value": 1950000.0, "sq_ft": 4800.0, "discount_pct": 15.0, "days_pipeline_to_win": 0, "stage": "Pipeline", "feedback_pending": 0, "feedback_notes": "BOQ under verification", "owner_name": "Skyline Architecture Studio"},
    {"id": "PRJ-106", "project_name": "Lodha Belmondo Riverside Lounge", "client_name": "Lodha Group", "location": "Gahunje", "city": "Pune", "state": "Maharashtra", "country": "India", "financial_year": "FY 25-26", "month": 6, "day_bracket": "26-31", "category": "UltraShield Decking", "total_value": 5100000.0, "sq_ft": 12000.0, "discount_pct": 9.0, "days_pipeline_to_win": 45, "stage": "Win", "feedback_pending": 0, "feedback_notes": "Installation in progress", "owner_name": "Rohan Verma"},
    {"id": "PRJ-107", "project_name": "Alibaug Sunset Cliff Villa", "client_name": "Private Client", "location": "Awas Beach", "city": "Alibaug", "state": "Maharashtra", "country": "India", "financial_year": "FY 25-26", "month": 7, "day_bracket": "1-5", "category": "Architectural Beams", "total_value": 3400000.0, "sq_ft": 7100.0, "discount_pct": 11.5, "days_pipeline_to_win": 0, "stage": "Pipeline", "feedback_pending": 1, "feedback_notes": "Feedback pending from lead designer", "owner_name": "Skyline Architecture Studio"},
    {"id": "PRJ-108", "project_name": "Hyderabad IT Hub Skydeck", "client_name": "Mindspace REIT", "location": "HITEC City", "city": "Hyderabad", "state": "Telangana", "country": "India", "financial_year": "FY 25-26", "month": 7, "day_bracket": "6-10", "category": "UltraShield Decking", "total_value": 7800000.0, "sq_ft": 18500.0, "discount_pct": 6.5, "days_pipeline_to_win": 30, "stage": "Win", "feedback_pending": 0, "feedback_notes": "Completed", "owner_name": "Super Administrator"},
    {"id": "PRJ-109", "project_name": "Chennai ECR Beach House", "client_name": "Greenfield Homes", "location": "ECR Road", "city": "Chennai", "state": "Tamil Nadu", "country": "India", "financial_year": "FY 25-26", "month": 8, "day_bracket": "11-15", "category": "All-Weather Cladding", "total_value": 2600000.0, "sq_ft": 6000.0, "discount_pct": 14.0, "days_pipeline_to_win": 0, "stage": "Pipeline", "feedback_pending": 1, "feedback_notes": "Awaiting quote signoff", "owner_name": "Lumber Life Premier Partner"},
    {"id": "PRJ-110", "project_name": "Kolkata Eco Park Boardwalk", "client_name": "WBHIDCO", "location": "New Town", "city": "Kolkata", "state": "West Bengal", "country": "India", "financial_year": "FY 25-26", "month": 8, "day_bracket": "16-20", "category": "UltraShield Decking", "total_value": 8900000.0, "sq_ft": 21000.0, "discount_pct": 5.0, "days_pipeline_to_win": 50, "stage": "Win", "feedback_pending": 0, "feedback_notes": "Delivered", "owner_name": "Super Administrator"},
    {"id": "PRJ-111", "project_name": "Udaipur Lakeview Heritage Courtyard", "client_name": "HRH Group", "location": "Lake Pichola", "city": "Udaipur", "state": "Rajasthan", "country": "India", "financial_year": "FY 25-26", "month": 9, "day_bracket": "21-25", "category": "Architectural Pergola", "total_value": 4100000.0, "sq_ft": 8800.0, "discount_pct": 9.5, "days_pipeline_to_win": 0, "stage": "Pipeline", "feedback_pending": 1, "feedback_notes": "Material sample pending test", "owner_name": "Rohan Verma"},
    {"id": "PRJ-112", "project_name": "Jaipur Fairmont Pool Deck", "client_name": "Fairmont Hotels", "location": "Kukas", "city": "Jaipur", "state": "Rajasthan", "country": "India", "financial_year": "FY 25-26", "month": 9, "day_bracket": "26-31", "category": "UltraShield Decking", "total_value": 5700000.0, "sq_ft": 13400.0, "discount_pct": 8.0, "days_pipeline_to_win": 35, "stage": "Win", "feedback_pending": 0, "feedback_notes": "Finished", "owner_name": "Super Administrator"},
    {"id": "PRJ-113", "project_name": "Ahmedabad Riverfront Pavilion", "client_name": "Sabarmati DCL", "location": "Riverfront West", "city": "Ahmedabad", "state": "Gujarat", "country": "India", "financial_year": "FY 25-26", "month": 10, "day_bracket": "1-5", "category": "Composite Decking", "total_value": 6500000.0, "sq_ft": 15200.0, "discount_pct": 7.5, "days_pipeline_to_win": 0, "stage": "Pipeline", "feedback_pending": 1, "feedback_notes": "Structural engineer review", "owner_name": "Rohan Verma"},
    {"id": "PRJ-114", "project_name": "Kochi Marina Yacht Club", "client_name": "Kerala Tourism", "location": "Bolgatty Island", "city": "Kochi", "state": "Kerala", "country": "India", "financial_year": "FY 25-26", "month": 10, "day_bracket": "6-10", "category": "UltraShield Decking", "total_value": 4800000.0, "sq_ft": 11000.0, "discount_pct": 10.0, "days_pipeline_to_win": 40, "stage": "Win", "feedback_pending": 0, "feedback_notes": "Completed", "owner_name": "Lumber Life Premier Partner"},
    {"id": "PRJ-115", "project_name": "Chandigarh Sector 9 Residence", "client_name": "Ar. Mehta & Assoc", "location": "Sector 9", "city": "Chandigarh", "state": "Punjab", "country": "India", "financial_year": "FY 25-26", "month": 11, "day_bracket": "11-15", "category": "Exterior Cladding", "total_value": 2200000.0, "sq_ft": 5100.0, "discount_pct": 13.0, "days_pipeline_to_win": 0, "stage": "Pipeline", "feedback_pending": 1, "feedback_notes": "Feedback pending on Peruvian Teak finish", "owner_name": "Skyline Architecture Studio"},
    {"id": "PRJ-116", "project_name": "Noida Cyber One Rooftop", "client_name": "Bhutani Group", "location": "Sector 140A", "city": "Noida", "state": "Uttar Pradesh", "country": "India", "financial_year": "FY 25-26", "month": 11, "day_bracket": "16-20", "category": "Composite Decking", "total_value": 5400000.0, "sq_ft": 12800.0, "discount_pct": 8.0, "days_pipeline_to_win": 36, "stage": "Win", "feedback_pending": 0, "feedback_notes": "Won", "owner_name": "Super Administrator"},
    {"id": "PRJ-117", "project_name": "Lonavala Hilltop Bungalow", "client_name": "Signature Estates", "location": "Tungarli", "city": "Lonavala", "state": "Maharashtra", "country": "India", "financial_year": "FY 25-26", "month": 12, "day_bracket": "21-25", "category": "UltraShield Decking", "total_value": 3100000.0, "sq_ft": 7200.0, "discount_pct": 11.0, "days_pipeline_to_win": 0, "stage": "Pipeline", "feedback_pending": 1, "feedback_notes": "Budget re-allocation in progress", "owner_name": "Lumber Life Premier Partner"},
    {"id": "PRJ-118", "project_name": "Surat Diamond Bourse Walkways", "client_name": "SDB Committee", "location": "DREAM City", "city": "Surat", "state": "Gujarat", "country": "India", "financial_year": "FY 25-26", "month": 12, "day_bracket": "26-31", "category": "UltraShield Decking", "total_value": 9400000.0, "sq_ft": 22500.0, "discount_pct": 6.0, "days_pipeline_to_win": 28, "stage": "Win", "feedback_pending": 0, "feedback_notes": "Delivered", "owner_name": "Super Administrator"},
    {"id": "PRJ-119", "project_name": "Dehradun Pines Mountain Villa", "client_name": "Pines Retreat", "location": "Mussoorie Rd", "city": "Dehradun", "state": "Uttarakhand", "country": "India", "financial_year": "FY 25-26", "month": 1, "day_bracket": "1-5", "category": "Exterior Cladding", "total_value": 2700000.0, "sq_ft": 6300.0, "discount_pct": 12.0, "days_pipeline_to_win": 0, "stage": "Pipeline", "feedback_pending": 0, "feedback_notes": "Under review", "owner_name": "Rohan Verma"},
    {"id": "PRJ-120", "project_name": "Indore Super Corridor Tech Park", "client_name": "Brilliant Estates", "location": "Super Corridor", "city": "Indore", "state": "Madhya Pradesh", "country": "India", "financial_year": "FY 25-26", "month": 2, "day_bracket": "6-10", "category": "UltraShield Decking", "total_value": 4300000.0, "sq_ft": 10200.0, "discount_pct": 9.0, "days_pipeline_to_win": 33, "stage": "Win", "feedback_pending": 0, "feedback_notes": "Invoiced", "owner_name": "Super Administrator"},
]

print(f"Loaded {len(pipeline_projects)} sample projects successfully.")
